spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#        format_sql: true
#    show-sql: true
    defer-datasource-initialization: true
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:postgres}?autoReconnect=true;
    username: ${DB_UNAME:postgres}
    password: ${DB_PASS:1234}
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 30
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_HOST:http://localhost:9090/realms/social_media}
          jwk-set-uri: ${KEYCLOAK_JWKS:http://localhost:9090/realms/social_media/protocol/openid-connect/certs}
minio:
  endpoint: ${MINIO_URL:http://localhost:9001}
  access-key: ${MINIO_ACCESS:minioadmin}
  secret-key: ${MINIO_SECRET:minioadmin}
  bucket-name: ${MINIO_DEFAULT_BUCKET:social-media}
  secure: false

